#!/bin/bash

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --py jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy
jupyter lab build

code-server --install-extension ms-python.python

# Install the VS code proxy
pip install -e.




rm -rf /var/lib/apt/lists/*

# Install .NET Core SDK
export DOTNET_SDK_VERSION="3.1.101"

curl -SL --output dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz \
    && dotnet_sha512='eeee75323be762c329176d5856ec2ecfd16f06607965614df006730ed648a5b5d12ac7fd1942fe37cfc97e3013e796ef278e7c7bc4f32b8680585c4884a8a6a1' \
    && echo "$dotnet_sha512 dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /home/jovyan/dotnet \
    && tar -zxf dotnet.tar.gz -C /home/jovyan/dotnet \
    && rm dotnet.tar.gz
#    && ln -s /home/jovyan/dotnet/dotnet /usr/bin/dotnet

# Enable detection of running in a container
export DOTNET_RUNNING_IN_CONTAINER=true
    # Enable correct mode for dotnet watch (only mode supported in a container)
export   DOTNET_USE_POLLING_FILE_WATCHER=true
    # Skip extraction of XML docs - generally not useful within an image/container - helps performance
export    NUGET_XMLDOC_MODE=skip
    # Opt out of telemetry until after we install jupyter when building the image, this prevents caching of machine id
export    DOTNET_TRY_CLI_TELEMETRY_OPTOUT=true

# Trigger first run experience by running arbitrary cmd
/home/jovyan/dotnet/dotnet/dotnet help
